services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./test/db/data:/var/lib/mysql # 생성된 데이터 저장 위치
      - ./test/db/conf.d:/etc/mysql/conf.d # my.cnf 세팅
      - ./test/db/sql:/docker-entrypoint-initdb.d # 초기데이터 설정
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      timeout: 5s

  server:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
